In [ ]:
from pandas import DataFrame

from pandas import Series
from pandas import concat
from pandas import read_csv
from pandas import datetime
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from math import sqrt
from matplotlib import pyplot
import numpy
import numpy as np
import keras
import matplotlib.pyplot as plt
import pandas as pd
import glob
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error
from sklearn.utils import shuffle
import sys
from pandas import DataFrame
import math
from sklearn.metrics import mean_squared_error
from keras.optimizers import Adam
from keras import backend as K
import tensorflow as tf
import gc
from contextlib import redirect_stdout
import os

In [ ]:
os.chdir('/content/drive/My Drive/New LSTM Crack')

In [ ]:
data_1 = glob.glob('./Test/1700N*.csv')
data1_df = pd.concat([pd.read_csv(f) for f in data_1])
print(data1_df)
data1 = np.asarray(data1_df)

               Time  Crack Length  Time Difference  Force
0        175.976563      0.051697          0.00000   1700
1        176.171873      0.062551          0.19531   1700
2        176.367183      0.072248          0.39062   1700
3        176.562503      0.102847          0.58594   1700
4        176.757813      0.088103          0.78125   1700
...             ...           ...              ...    ...
68047  18667.186770      0.476033      18491.21021   1700
68048  18667.381770      0.474235      18491.40521   1700
68049  18667.576770      0.480974      18491.60021   1700
68050  18667.772770      0.477759      18491.79621   1700
68051  18667.967770      0.478020      18491.99121   1700

[68052 rows x 4 columns]


In [ ]:
data_2 = glob.glob('./Test/1600N*.csv')
data2_df = pd.concat([pd.read_csv(f) for f in data_2])
print(data2_df)
data2 = np.asarray(data2_df)

               Time  Crack Length  Time Difference  Force
0        175.976567      0.089759          0.00000   1600
1        176.171877      0.080669          0.19531   1600
2        176.367187      0.085982          0.39062   1600
3        176.562497      0.086022          0.58593   1600
4        176.757817      0.060482          0.78125   1600
...             ...           ...              ...    ...
68047  18666.601800      0.375097      18490.62523   1600
68048  18666.796800      0.339379      18490.82023   1600
68049  18666.991800      0.404461      18491.01523   1600
68050  18667.187800      0.347728      18491.21123   1600
68051  18667.382800      0.387156      18491.40623   1600

[68052 rows x 4 columns]


In [ ]:
print(data1[:,0])
print(data2[:,0])

[  175.9765634   176.1718734   176.3671834 ... 18667.57677   18667.77277
 18667.96777  ]
[  175.9765669   176.1718769   176.3671869 ... 18666.9918    18667.1878
 18667.3828   ]


In [ ]:
time = ((data1[:, 0] + data2[:, 0]) / 2.0).reshape(len(data1),1)
crack_length = ((data1[:, 1] + data2[:, 1]) / 2.0).reshape(len(data1),1)
time_diff = ((data1[:, 2] + data2[:, 2]) / 2.0).reshape(len(data1),1)
force = ((data1[:, 3] + data2[:, 3]) / 2.0).reshape(len(data1),1)

In [ ]:
combined_data = np.hstack((time, crack_length, time_diff, force))
print(combined_data)

[[1.75976565e+02 7.07283260e-02 0.00000000e+00 1.65000000e+03]
 [1.76171875e+02 7.16100045e-02 1.95310000e-01 1.65000000e+03]
 [1.76367185e+02 7.91149350e-02 3.90620000e-01 1.65000000e+03]
 ...
 [1.86672843e+04 4.42717815e-01 1.84913077e+04 1.65000000e+03]
 [1.86674803e+04 4.12743735e-01 1.84915037e+04 1.65000000e+03]
 [1.86676753e+04 4.32587952e-01 1.84916987e+04 1.65000000e+03]]


In [ ]:
np.savetxt('Testing_data_1650.csv', combined_data, delimiter=",", header='Time, Crack Length, Time Difference, Force')